name: flutter_news_app_bilingual
description: "A bilingual English-Vietnamese news reader built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.2
  http: ^1.2.2
  xml: ^6.5.0
  flex_color_scheme: ^8.3.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  flutter_widget_from_html: ^0.17.1
  html: ^0.15.4
  url_launcher: ^6.3.2
  firebase_core: ^3.7.0
  firebase_auth: ^5.4.0
  webview_flutter: ^4.7.0
  shared_preferences: ^2.3.3
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/data/
  
  fonts:
    - family: Bookerly
      fonts:
        - asset: "assets/fonts/Bookerly.ttf"
        - asset: "assets/fonts/Bookerly Italic.ttf"
          style: italic
        - asset: "assets/fonts/Bookerly Bold.ttf"
          weight: 700
        - asset: "assets/fonts/Bookerly Bold Italic.ttf"
          weight: 700
          style: italic
